import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {XCookieAdapter,cookieAuth,webQuery} from '../lib/scout/adapters/x-cookie.mjs';
import {ReadTransport} from '../lib/scout/transport.mjs';
import {normalizeGraphql,graphqlFailure} from '../lib/scout/web/normalize-graphql.mjs';
import {webMetadata,bundleUrls,extractQueryIds,resetWebMetadata} from '../lib/scout/web/bootstrap.mjs';
import {SnapshotAdapter,validateSnapshot} from '../lib/scout/adapters/snapshot.mjs';
import {runTool,createService} from '../lib/scout/service.mjs';
import {POST_SCHEMA,validate} from '../lib/scout/schema.mjs';
import {freeRuntimeProbe} from '../lib/free-runtime-probe.mjs';
import {ScoutError} from '../lib/scout/errors.mjs';
const at=new Date(Date.now()-60000).toISOString();
const token='SYNTHETIC_AUTH_1234567890',csrf='SYNTHETIC_CSRF_1234567890',bearer='AAAAA'+'SYNTHETIC_PUBLIC_WEB_'.repeat(4);
const ids={SearchTimeline:'READ_SEARCH_ID',UserByScreenName:'READ_USER_ID',UserTweetsAndReplies:'READ_TIMELINE_ID',TweetResultByRestId:'READ_POST_ID'};
const env={X_AUTH_TOKEN:token,X_CT0:csrf,X_WEB_BEARER:bearer,X_WEB_QUERY_IDS_JSON:JSON.stringify(ids)};
const reply=(id='100',handle='fixture_user')=>({__typename:'Tweet',rest_id:id,legacy:{full_text:'Synthetic new AI demo https://github.com/example/fixture',created_at:at,favorite_count:3,retweet_count:2,reply_count:1,quote_count:1,entities:{urls:[{expanded_url:'https://github.com/example/fixture'}]},in_reply_to_status_id_str:'80',in_reply_to_user_id_str:'8',in_reply_to_screen_name:'fixture_parent',quoted_status_id_str:'90',extended_entities:{media:[{id_str:'m1',type:'video',media_url_https:'https://pbs.twimg.com/fixture.jpg',video_info:{duration_millis:1234}}]}},core:{user_results:{result:{rest_id:'7',core:{screen_name:handle,name:'Fixture User'},legacy:{email:'never-return@example.com',location:'never-return'}}}},quoted_status_result:{result:{__typename:'Tweet',rest_id:'90',legacy:{full_text:'Quote fixture',created_at:at},core:{user_results:{result:{rest_id:'8',legacy:{screen_name:'fixture_parent',name:'Parent'}}}}}},note_tweet:{note_tweet_results:{result:{text:'Long synthetic AI demo text',entity_set:{urls:[{expanded_url:'https://arxiv.org/abs/0000.00000'}]}}}},views:{count:'30'}});
const timeline=(posts=[reply()])=>({data:{search_by_raw_query:{search_timeline:{timeline:{instructions:[{type:'TimelineAddEntries',entries:posts.map(p=>({content:{itemContent:{tweet_results:{result:p}}}})).concat([{content:{cursorType:'Bottom',value:'NEXT_SYNTHETIC_CURSOR'}}])}]}}}}});
const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json',...headers}});
class Memory{failed=false;rows=new Map();async state(){return[...this.rows.values()];}async setState(id,code,retry_at=null){this.rows.set(id,{id,code,retry_at,checked_at:new Date().toISOString()});}async observe(){return new Map();}async health(){return'ok';}}
const adapter=()=>({id:'x_cookie',capabilities:['get_post','get_user_posts','search_x'],configured:()=>true,get_post:async()=>normalizeGraphql(timeline()),get_user_posts:async()=>normalizeGraphql(timeline()),search_x:async()=>normalizeGraphql(timeline())});
test('production rejects paid backend configuration even with a credential present',async()=>{let calls=0;for(const backend of['x_api','http_bridge','x_cookie,x_api']){const r=await runTool('get_post',{id:'100'},{X_SCOUT_BACKENDS:backend,X_API_BEARER_TOKEN:'SYNTHETIC_OLD_KEY'},{fetcher:async()=>{calls++;throw Error();},store:new Memory()});assert.equal(r.status,'config_error');}assert.equal(calls,0);});
test('cookie implementation has only fixed GraphQL GET read operations',async()=>{const seen=[];const a=new XCookieAdapter(env,new ReadTransport({fetcher:async(url,init)=>{seen.push({url,init});const op=new URL(url).pathname.split('/').at(-1);return json(op==='UserByScreenName'?{data:{user:{result:{rest_id:'7',core:{screen_name:'fixture_user'}}}}}:timeline());}}));await a.get_post({id:'100'});await a.get_user_posts({handle:'fixture_user'});await a.search_x({query:'AI -is:retweet',start_time:at,end_time:new Date().toISOString()});assert(seen.every(c=>c.init.method==='GET'&&c.init.redirect==='manual'&&new URL(c.url).origin==='https://x.com'));assert(seen.every(c=>c.init.headers.Cookie==='auth_token='+token+'; ct0='+csrf&&c.init.headers['x-csrf-token']===csrf));assert(!seen.some(c=>c.url.includes(token)||c.url.includes(csrf)));for(const op of['CreateTweet','FavoriteTweet','CreateRetweet','Follow','SendDM','Bookmarks'])await assert.rejects(a.request(op,{}),/INVALID_INPUT/);});
test('cookie parser rejects missing, malformed and header-injection secrets safely',()=>{assert.throws(()=>cookieAuth({}),/AUTH_MISSING/);for(const v of['short','bad\r\nX-Header:evil','invalid; second=cookie'])assert.throws(()=>cookieAuth({X_AUTH_TOKEN:v,X_CT0:csrf}),e=>e.code==='CONFIG_INVALID'&&!e.message.includes(v));});
test('GraphQL normalizer preserves source, author, time, long text, replies, quotes and media',()=>{const r=normalizeGraphql(timeline());assert.equal(r.posts.length,1);const p=r.posts[0];validate(POST_SCHEMA,p);assert.equal(p.url,'https://x.com/fixture_user/status/100');assert.equal(p.author.name,'Fixture User');assert.equal(p.created_at,at);assert.equal(p.text,'Long synthetic AI demo text');assert.equal(p.relationships.find(x=>x.type==='reply').url,'https://x.com/fixture_parent/status/80');assert.equal(p.quote_urls[0],'https://x.com/fixture_parent/status/90');assert.equal(p.has_video,true);assert.equal(p.metrics.views,30);assert.equal(r.next_cursor,'NEXT_SYNTHETIC_CURSOR');assert(!JSON.stringify(r).includes('never-return'));});
test('repost relationships are retained without returning nested post as a separate search hit',()=>{const p=reply();p.retweeted_status_result={result:{...reply('70','original_author'),quoted_status_result:undefined}};const r=normalizeGraphql(timeline([p]));assert.equal(r.posts.length,1);assert.equal(r.posts[0].relationships.find(x=>x.type==='repost').post_id,'70');});
test('GraphQL empty timeline differs from malformed, tombstoned and protected results',()=>{assert.equal(normalizeGraphql(timeline([])).posts.length,0);assert.throws(()=>normalizeGraphql({data:{new_shape:[]}}),/UPSTREAM_SCHEMA_CHANGED/);assert.throws(()=>normalizeGraphql({data:{tweetResult:{result:{__typename:'TweetUnavailable'}}}},{id:'100'}),/NOT_FOUND/);const p=reply();p.core.user_results.result.legacy.protected=true;assert.equal(normalizeGraphql(timeline([p])).posts.length,0);assert.throws(()=>normalizeGraphql(timeline([p]),{id:'100'}),/ACCESS_DENIED/);});
test('GraphQL authentication, locked account, rate and shape errors never expose messages',()=>{for(const[code,expected]of[[89,'AUTH_EXPIRED'],[326,'FREE_BACKEND_BLOCKED'],[88,'RATE_LIMITED'],[144,'NOT_FOUND']])assert.equal(graphqlFailure({errors:[{code,message:token}]}),expected);assert.equal(graphqlFailure({errors:[{message:'feature is missing '+token}]}),'UPSTREAM_SCHEMA_CHANGED');});
for(const status of[403,402,302])test('free HTTP '+status+' returns FREE_BACKEND_BLOCKED',async()=>{const a=new XCookieAdapter(env,new ReadTransport({fetcher:async()=>json({message:token},status)}));await assert.rejects(a.search_x({query:'AI'}),e=>e.code==='FREE_BACKEND_BLOCKED'&&!e.message.includes(token));});
test('free HTML challenge stops without bypass, paid fallback or fabricated empty results',async()=>{const a=new XCookieAdapter(env,new ReadTransport({fetcher:async()=>new Response('captcha '+token,{headers:{'content-type':'text/html'}})}));await assert.rejects(a.search_x({query:'AI'}),/FREE_BACKEND_BLOCKED/);});
test('stale query ID is a schema change, no alternate request or retry',async()=>{let calls=0;const a=new XCookieAdapter(env,new ReadTransport({fetcher:async()=>{calls++;return json({},404);}}));await assert.rejects(a.search_x({query:'AI'}),/UPSTREAM_SCHEMA_CHANGED/);assert.equal(calls,1);});
test('legacy and current web asset paths are origin-bound; imported relative assets remain public',()=>{const refs=bundleUrls('<script src="https://abs.twimg.com/x-web/x-web/main-test.js"></script> https://evil.example/main.js');assert.equal(refs.length,1);assert.deepEqual(bundleUrls('import "./api-test.js"; import "https://evil.example/a.js";',refs[0]),['https://abs.twimg.com/x-web/x-web/api-test.js']);assert.deepEqual(bundleUrls('import "../../../../secret.js"',refs[0]),[]);const q=extractQueryIds('queryId:"READ_SEARCH_ID",operationName:"SearchTimeline";queryId:"WRITE_XYZ_ID",operationName:"CreateTweet"');assert.deepEqual(q,{SearchTimeline:'READ_SEARCH_ID'});});
test('bootstrap sends cookie only to x.com, not abs.twimg.com, and never returns config values',async()=>{resetWebMetadata();const seen=[];const t=new ReadTransport({fetcher:async(url,init)=>{seen.push({url,init});return new Response(url==='https://x.com/'?'<script src="https://abs.twimg.com/x-web/x-web/main-fixture.js"></script>':'token="'+bearer+'";'+Object.entries(ids).map(([op,id])=>'queryId:"'+id+'",operationName:"'+op+'"').join(';'));}});const m=await webMetadata({},t,{cookie:'auth_token='+token+'; ct0='+csrf,force:true});assert(m.qids.SearchTimeline);assert.equal(seen[0].init.headers.Cookie.includes(token),true);assert.equal(seen[1].init.headers.Cookie,undefined);const p=await freeRuntimeProbe({}, {fetcher:async url=>new Response(url==='https://x.com/'?'<script src="https://abs.twimg.com/x-web/x-web/main-fixture.js"></script>':'token="'+bearer+'";'+Object.entries(ids).map(([op,id])=>'queryId:"'+id+'",operationName:"'+op+'"').join(';'))});assert.equal(p.parser_fixture,'passed');assert(!JSON.stringify(p).includes(bearer));assert.equal(p.real_authenticated_retrieval,'not_proven');resetWebMetadata();});
test('time-bounded browser search remains Latest and maps repost syntax',()=>{const q=webQuery('AI -is:retweet','2026-10-04T20:00:00Z','2026-10-05T20:00:00Z');assert(q.includes('-filter:retweets'));assert(q.includes('since:2026-10-04 until:2026-10-06'));});
test('FREE_BACKEND_BLOCKED never automatically rotates to snapshot',async()=>{let fall=0;const a=adapter();a.search_x=async()=>{throw new ScoutError('FREE_BACKEND_BLOCKED')};const b={...adapter(),id:'snapshot',search_x:async()=>{fall++;return normalizeGraphql(timeline());}};const r=await runTool('search_x',{query:'AI'},{X_SCOUT_BACKENDS:'x_cookie,snapshot'},{adapterOverrides:[a,b],store:new Memory()});assert.equal(fall,0);assert.equal(r.coverage.reason,'FREE_BACKEND_BLOCKED');assert.equal(r.continue_source_watch,true);});
test('cookie secrets and web token cannot escape echoed posts, error messages or MCP output',async()=>{for(const key of['X_AUTH_TOKEN','X_CT0','X_WEB_BEARER']){const a=adapter();a.get_post=async()=>{const r=normalizeGraphql(timeline());r.posts[0].text='Reflection '+env[key];return r;};const r=await runTool('get_post',{id:'100'},env,{adapterOverrides:[a],store:new Memory()});assert(!JSON.stringify(r).includes(env[key]));assert(r.posts[0].text.includes('[REDACTED]'));a.get_post=async()=>{throw Error(env[key])};assert(!JSON.stringify(await runTool('get_post',{id:'100'},env,{adapterOverrides:[a],store:new Memory()})).includes(env[key]));}});
test('search blocked independently keeps timeline health partial',async()=>{const a=adapter();a.search_x=async()=>{throw new ScoutError('FREE_BACKEND_BLOCKED')};const service=await createService(env,{adapterOverrides:[a],store:new Memory()});await service.execute('search_x',{query:'AI'});assert.equal((await service.execute('get_user_posts',{handle:'fixture_user'})).posts.length,1);const h=await service.execute('health_check',{});assert.equal(h.status,'partial');assert.equal(h.health.free_backend_state,'FREE_BACKEND_BLOCKED');assert.equal(h.health.paid_backends_allowed,false);});
const snapshot=()=>({version:1,generated_at:new Date().toISOString(),user_posts:{fixture_user:{posts:normalizeGraphql(timeline()).posts,errors:[]}},searches:{'AI demo':{posts:normalizeGraphql(timeline()).posts,errors:[]}}});
test('snapshot consumes normalized captured posts and explicit captured queries only',async()=>{const a=new SnapshotAdapter({X_SCOUT_SNAPSHOT_URL:'https://raw.githubusercontent.com/example/repo/main/data/x-scout-snapshot.json'},new ReadTransport({fetcher:async(url,init)=>{assert.equal(init.method,'GET');assert.equal(init.headers.Authorization,undefined);assert.equal(init.headers.Cookie,undefined);return json(snapshot());}}));assert.equal((await a.get_post({id:'100'})).posts[0].provenance.backend,'snapshot');assert.equal((await a.get_user_posts({handle:'fixture_user'})).posts.length,1);await assert.rejects(a.search_x({query:'unseen topic'}),/SNAPSHOT_QUERY_NOT_CAPTURED/);});
test('snapshot stale, malformed and unsafe origins do not produce successful data',async()=>{const s=snapshot();s.generated_at=new Date(Date.now()-31*3600000).toISOString();assert.throws(()=>validateSnapshot(s),/SNAPSHOT_STALE/);for(const url of['https://api.x.com/x-scout-snapshot.json','http://raw.githubusercontent.com/o/r/main/data/x-scout-snapshot.json','https://user:secret@raw.githubusercontent.com/o/r/main/data/x-scout-snapshot.json']){const a=new SnapshotAdapter({X_SCOUT_SNAPSHOT_URL:url},new ReadTransport());await assert.rejects(a.load(),/CONFIG_INVALID/);}});
test('production source imports neither archived official API nor generic bridge',async()=>{const src=await readFile(new URL('../lib/scout/service.mjs',import.meta.url),'utf8');assert(!src.includes('adapters/x-api'));assert(!src.includes('adapters/http-bridge'));assert(!src.includes('X_API_BEARER_TOKEN'));const schema=await readFile(new URL('../docs/schema.sha256',import.meta.url),'utf8');assert(schema.trim());});
test('free capture stops after a blocked session and emits no Cookie in its public snapshot',async()=>{const{captureSnapshot}=await import('../fetcher/capture.mjs');let calls=0;const config={version:1,accounts:[{handle:'fixture_user',group:'one',high_signal:true},{handle:'fixture_parent',group:'two',high_signal:true}],discovery_queries:['AI demo']};const result=await captureSnapshot({...env,X_SCOUT_WATCHLIST_JSON:JSON.stringify(config)},{invoke:async()=>{calls++;return {posts:[],errors:[{code:'FREE_BACKEND_BLOCKED',message:token}]};}});assert.equal(calls,1);assert.equal(result.user_posts.fixture_parent.errors[0].code,'FREE_BACKEND_BLOCKED');assert(!JSON.stringify(result).includes(token));assert(!JSON.stringify(result).includes(csrf));});
test('free capture retains broad queries, public metadata and redacts a malicious reflection',async()=>{const{captureSnapshot}=await import('../fetcher/capture.mjs');const calls=[];const config={version:1,accounts:[{handle:'fixture_user',group:'one',high_signal:true}],discovery_queries:['AI demo']};const result=await captureSnapshot({...env,X_SCOUT_WATCHLIST_JSON:JSON.stringify(config),X_SCOUT_FETCH_PLAN_JSON:JSON.stringify({entities:['Synthetic Model'],queries:[]})},{invoke:async(name,args)=>{calls.push({name,args});const r=normalizeGraphql(timeline());r.posts[0].text+=' '+token+' '+csrf;return {...r,errors:[]};}});assert(calls.some(c=>c.name==='search_x'&&c.args.query==='AI demo'));assert(calls.some(c=>c.name==='search_x'&&c.args.query.includes('Synthetic Model')));assert(!JSON.stringify(result).includes(token));assert(!JSON.stringify(result).includes(csrf));assert.equal(result.user_posts.fixture_user.posts[0].relationships[0].post_id,'80');});
test('failed bootstrap is shared within one tool call instead of repeated Cookie probes',async()=>{resetWebMetadata();let reads=0;const a=new XCookieAdapter({X_AUTH_TOKEN:token,X_CT0:csrf},new ReadTransport({fetcher:async()=>{reads++;return json({},403);}}));await assert.rejects(a.get_user_posts({handle:'fixture_user'}),/FREE_BACKEND_BLOCKED/);await assert.rejects(a.search_x({query:'AI'}),/FREE_BACKEND_BLOCKED/);assert.equal(reads,1);});
test('injected Query ID write operation is refused before any network request',async()=>{let calls=0;const a=new XCookieAdapter({...env,X_WEB_QUERY_IDS_JSON:JSON.stringify({CreateTweet:'WRITE_OPERATION_ID'})},new ReadTransport({fetcher:async()=>{calls++;return json({});}}));await assert.rejects(a.get_post({id:'100'}),/CONFIG_INVALID/);assert.equal(calls,0);});
test('MCP returns business health failures as canonical data without a platform argument-error alias',async()=>{const{handleMcp}=await import('../lib/scout/mcp.mjs');const r=await(await handleMcp(new Request('https://example.com/mcp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'health_check',arguments:{}}})}),{}, {store:new Memory()})).json();assert.equal(r.result.isError,false);assert.equal(r.result.structuredContent.status,'auth_required');assert.deepEqual(JSON.parse(r.result.content[0].text),r.result.structuredContent);});
test('Dots reads platform Plugin envelopes while preserving the original Source Watch pool',async()=>{const{optionalXScout}=await import('../docs/dots-integration.mjs');const source=[{id:'official'}];const r=await optionalXScout({sourceCandidates:source,callTool:async()=>({content:[{type:'text',text:JSON.stringify({schema_version:'1.0.0',status:'auth_required'})}]})});assert.deepEqual(r.sourceCandidates,source);assert.equal(r.xStatus,'auth_required');});

 test('owner authenticated metadata diagnostic sends Cookie only to X and redacts reflections',async()=>{resetWebMetadata();const calls=[];const r=await freeRuntimeProbe(env,{authenticated:true,fetcher:async(url,init)=>{calls.push({url,init});return new Response(url==='https://x.com/'?'<script src="https://abs.twimg.com/x-web/x-web/'+token+'.js"></script>':'token="'+bearer+'";'+Object.entries(ids).map(([op,id])=>'queryId:"'+id+'",operationName:"'+op+'"').join(';'));}});assert.equal(r.metadata_request_authenticated,true);assert.equal(calls[0].init.headers.Cookie,'auth_token='+token+'; ct0='+csrf);assert.equal(calls[1].init.headers.Cookie,undefined);assert(!JSON.stringify(r).includes(token));assert(!JSON.stringify(r).includes(csrf));assert(!JSON.stringify(r).includes(bearer));resetWebMetadata();});

test('deep metadata diagnostics expose only codes and field names, never X personal fields or messages',async()=>{resetWebMetadata();const r=await freeRuntimeProbe(env,{authenticated:true,deep:true,fetcher:async(url)=>{if(url==='https://x.com/')return new Response('<script src="https://abs.twimg.com/x-web/x-web/main-fixture.js"></script>');if(url.startsWith('https://abs.twimg.com/'))return new Response('token="'+bearer+'";'+Object.entries(ids).map(([op,id])=>'queryId:"'+id+'",operationName:"'+op+'"').join(';'));return json({data:{user:{result:{rest_id:'7',email:'PII_NEVER_RETURN'}}},errors:[{code:89,message:'PII_NEVER_RETURN '+token}]});}});assert.equal(r.capability_checks[0].error.code,'AUTH_EXPIRED');assert.equal(r.capability_checks.length,1);assert(!JSON.stringify(r).includes('PII_NEVER_RETURN'));assert(!JSON.stringify(r).includes(token));assert(!JSON.stringify(r).includes(bearer));resetWebMetadata();});

test('metadata page diagnostics cannot redirect credentials to another host or a write route',async()=>{let calls=0;for(const page of['https://evil.example/home','https://x.com/i/api/graphql/write/CreateTweet','https://evil@x.com/home'])await assert.rejects(webMetadata(env,new ReadTransport({fetcher:async()=>{calls++;throw Error();}}),{cookie:'auth_token='+token,page}),/CONFIG_INVALID/);assert.equal(calls,0);});

test('obsolete reply operation preserves ordinary timeline with explicit incomplete reply coverage',async()=>{const calls=[];const e={...env,X_WEB_QUERY_IDS_JSON:JSON.stringify({...ids,UserTweets:'READ_POSTS_ONLY_ID'})};const a=new XCookieAdapter(e,new ReadTransport({fetcher:async url=>{const op=new URL(url).pathname.split('/').at(-1);calls.push(op);return op==='UserByScreenName'?json({data:{user:{result:{rest_id:'7'}}}}):op==='UserTweetsAndReplies'?json({},404):json(timeline());}}));const r=await a.get_user_posts({handle:'fixture_user'});assert.equal(r.posts.length,1);assert(r.warnings.some(w=>w.code==='REPLY_COVERAGE_UNVERIFIED'));assert.deepEqual(calls,['UserByScreenName','UserTweetsAndReplies','UserTweets']);for(const status of[401,403,429,500]){const observed=[];const b=new XCookieAdapter(e,new ReadTransport({fetcher:async url=>{const op=new URL(url).pathname.split('/').at(-1);observed.push(op);return op==='UserByScreenName'?json({data:{user:{result:{rest_id:'7'}}}}):json({},status);}}));await assert.rejects(b.get_user_posts({handle:'fixture_user'}));assert(!observed.includes('UserTweets'));}});
test('owner pinned TweetDetail takes precedence over an automatically scraped stale single-post operation',async()=>{const e={...env,X_WEB_QUERY_IDS_JSON:JSON.stringify({TweetDetail:'READ_DETAIL_PIN_ID'})};resetWebMetadata();const calls=[];const a=new XCookieAdapter(e,new ReadTransport({fetcher:async url=>{calls.push(url);if(url==='https://x.com/')return new Response('<script src="https://abs.twimg.com/x-web/x-web/main-fixture.js"></script>');if(url.startsWith('https://abs.twimg.com/'))return new Response('token="'+bearer+'";'+Object.entries(ids).map(([op,id])=>'queryId:"'+id+'",operationName:"'+op+'"').join(';'));return json(timeline());}}));await a.get_post({id:'100'});assert(new URL(calls.at(-1)).pathname.endsWith('/READ_DETAIL_PIN_ID/TweetDetail'));resetWebMetadata();});

test('HTTP 400 cannot yield successful posts and a changed required feature is classified safely',async()=>{for(const[body,code]of[[timeline(),'UPSTREAM_REJECTED'],[{errors:[{message:'The following features cannot be null: synthetic_read_feature_enabled '+token}]},'UPSTREAM_SCHEMA_CHANGED']]){const a=new XCookieAdapter(env,new ReadTransport({fetcher:async()=>json(body,400)}));await assert.rejects(a.search_x({query:'AI'}),e=>e.code===code&&!e.message.includes(token));}});

test('Latest search follows owner browser read variables without Top mode or unrelated field toggles',async()=>{let seen;const a=new XCookieAdapter(env,new ReadTransport({fetcher:async url=>{seen=new URL(url);return json(timeline());}}));await a.search_x({query:'AI',limit:20});const v=JSON.parse(seen.searchParams.get('variables'));assert.equal(v.product,'Latest');assert.equal(v.withGrokTranslatedBio,false);assert.equal(v.withQuickPromoteEligibilityTweetFields,false);assert.equal(seen.searchParams.has('fieldToggles'),false);assert.equal(seen.pathname.split('/').at(-1),'SearchTimeline');});

test('browser search feature pin remains exact while other read operations keep their required defaults',async()=>{const e={...env,X_WEB_FEATURES_JSON:JSON.stringify({rweb_cashtags_enabled:true})};const seen=[];const a=new XCookieAdapter(e,new ReadTransport({fetcher:async url=>{seen.push(new URL(url));return json(timeline());}}));await a.search_x({query:'AI'});await a.get_post({id:'100'});assert.deepEqual(JSON.parse(seen[0].searchParams.get('features')),{rweb_cashtags_enabled:true});const p=JSON.parse(seen[1].searchParams.get('features'));assert.equal(p.rweb_cashtags_enabled,true);assert.equal(p.responsive_web_graphql_skip_user_profile_image_extensions_enabled,false);assert.equal(p.longform_notetweets_consumption_enabled,true);});

test('search schema failure blocks discovery without calling the working timeline fully ready or claiming an IP cause',async()=>{const a=adapter();a.search_x=async()=>{throw new ScoutError('UPSTREAM_SCHEMA_CHANGED')};const service=await createService(env,{adapterOverrides:[a],store:new Memory()});await service.execute('search_x',{query:'AI'});await service.execute('get_user_posts',{handle:'fixture_user'});const h=await service.execute('health_check',{});assert.equal(h.status,'partial');assert.equal(h.health.free_backend_state,'PARTIAL');assert.equal(h.health.free_discovery_state,'FREE_BACKEND_BLOCKED');assert.deepEqual(h.health.discovery_upstream_codes,['UPSTREAM_SCHEMA_CHANGED']);assert.equal(h.health.discovery_block_cause_confirmed,false);assert.equal(h.continue_source_watch,true);assert.equal(h.health.paid_backends_allowed,false);});

test('Dots uses the working Watchlist when discovery is blocked and preserves Source Watch without repeating failed searches',async()=>{const{optionalXScout}=await import('../docs/dots-integration.mjs');const calls=[];const source=[{id:'official'}];const candidate={id:'watchlist_candidate'};const r=await optionalXScout({sourceCandidates:source,entities:['Synthetic Model'],callTool:async(name)=>{calls.push(name);return name==='health_check'?{schema_version:'1.0.0',status:'partial',health:{free_discovery_state:'FREE_BACKEND_BLOCKED'}}:{schema_version:'1.0.0',status:'partial',posts:[{id:'100'}],candidates:[candidate],page:{next_watchlist_offset:null}};}});assert.deepEqual(calls,['health_check','scan_watchlist']);assert.deepEqual(r.sourceCandidates,source);assert.deepEqual(r.xCandidates,[candidate]);assert.equal(r.xDiscoveryStatus,'FREE_BACKEND_BLOCKED');assert.equal(r.xStatus,'partial');});

const acceptanceRow=(tool,posts=[],errors=[])=>({schema_version:'1.0.0',tool,status:errors.length?'auth_required':'ok',retrieved_at:at,posts,candidates:[],errors,warnings:[],coverage:{requested:1,succeeded:errors.length?0:1,failed:errors.length?1:0,complete:!errors.length,requests:0,reason:null},page:{next_cursor:null,next_watchlist_offset:null,has_more:false},health:null,continue_source_watch:true});
test('external acceptance stops the whole Cookie session on auth failure without losing its regression/discovery report',async()=>{const{runFetcherAcceptance}=await import('../fetcher/acceptance.mjs');let calls=0;const r=await runFetcherAcceptance(env,{invoke:async(name)=>{calls++;return acceptanceRow(name,[],[{code:'AUTH_EXPIRED',backend:'x_cookie',capability:name,retryable:false,retry_at:null}]);}});assert.equal(calls,1);assert.equal(r.session_terminal_code,'AUTH_EXPIRED');assert.equal(r.regression.status,'blocked_by_auth');assert.equal(r.unknown.status,'blocked_by_auth');assert.equal(r.paid_backends_allowed,false);assert.equal(r.primary_source_verification,'pending');});
test('external acceptance report redacts reflected Cookies in public posts and starts with handle/time only',async()=>{const{runFetcherAcceptance}=await import('../fetcher/acceptance.mjs');const post=normalizeGraphql({data:{tweetResult:{result:reply('100','thsottiaux')}}}).posts[0];post.text='28 days Codex Work ship one thing or full reset '+token+' '+csrf;const calls=[];const r=await runFetcherAcceptance(env,{invoke:async(name,args)=>{calls.push({name,args});return acceptanceRow(name,[post]);}});assert.equal(r.regression.status,'passed');assert.equal(calls[0].name,'get_user_posts');assert.equal(calls[0].args.handle,'thsottiaux');assert.equal(calls[0].args.id,undefined);assert(!JSON.stringify(calls[0].args).includes('/status/'));assert(!JSON.stringify(r).includes(token));assert(!JSON.stringify(r).includes(csrf));assert.equal(r.media_gap_verification,'pending');assert.equal(r.regression.post.relationships.length,2);});
